### ISSUE TITLE
Create another class like HashedString

### ISSUE THREAD

**Issue by rkhaslarov** [dmitry-vokhmin/string_task#1]
https://github.com/dmitry-vokhmin/string_task/blob/02dbb0cf8eb0e0ec7187ff34ee3a5d6fcd7a697e/main.py#L1

Create another class like HashedString and abstract class that would be their parent (perhaps, ABC module of Python will help with that).

Stack is highly depending on the both types, probably we need some abstraction for making it polymorphic?

**Comment by dmitry-vokhmin** [comment]
Done
